# Generated by Django 3.2.8 on 2021-10-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafkan_store', '0002_alter_kafkan_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kafkan',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
