# Generated by Django 3.2.7 on 2021-10-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafkan_store', '0002_auto_20211008_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kafkan',
            name='color',
            field=models.CharField(max_length=100),
        ),
    ]
