# Generated by Django 3.2.8 on 2021-10-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafkan_store', '0003_alter_kafkan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kafkan',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
