# Generated by Django 3.2.8 on 2021-10-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafkan_store', '0003_alter_kafkan_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='kafkan',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kafkan',
            name='name',
            field=models.CharField(default='Kafkan', max_length=250),
        ),
    ]
