# Generated by Django 3.2.8 on 2021-10-26 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kafkan_store', '0004_auto_20211012_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='kafkan',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kafkan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='kafkan',
            name='image',
            field=models.ImageField(upload_to='./media'),
        ),
        migrations.AlterField(
            model_name='kafkan',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
