# Generated by Django 3.2.8 on 2021-10-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafkan_store', '0005_kafkan_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kafkan',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
