# Generated by Django 3.2.8 on 2021-10-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafkan_store', '0007_alter_kafkan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kafkan',
            name='image',
            field=models.ImageField(upload_to='./media', verbose_name='Image'),
        ),
    ]
